name: Run Linter From Template

on:
  push:
    branches: [main]

permissions:
  checks: write

jobs:
  lint:
    uses: soso0024/ci-templates/.github/workflows/lint-python.yml@main
    with:
      python-version: "3.9"
